source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!
platform :ios, '8.0'

target 'GFayeSwift_Example' do
  pod 'GFayeSwift', :path => '../'
end

target 'GFayeSwift_Tests' do
  pod 'GFayeSwift', :path => '../'
end
